<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-07-11 14:57:24                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

$schema = new OnPhp\DBSchema();

?>