<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-07-11 14:57:24                    *
 *   This file is autogenerated - do not edit.                               *
 *****************************************************************************/

namespace Auto\Business;

use Business\User;

abstract class AutoUser
{
    protected $result = false;
    
    public function getResult()
    {
        return $this->result;
    }
    
    public function isResult()
    {
        return $this->result;
    }
    
    /**
     * @return User
    **/
    public function setResult($result = false)
    {
        $this->result = ($result === true);
    
        return $this;
    }
}