<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2017-07-11 14:57:24                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

namespace Proto;

use Auto\Proto\AutoProtoUser;

class ProtoUser extends AutoProtoUser
{
        /*_*/
}